import Head from 'next/head'
import Banner from '../components/Home/Banner';
import ProductCategories from '../components/Home/ProductCategories';

let Index = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <ProductCategories />
    </>
  )
}

export default Index;