export let ActionType = {
    GET_BANNERS: "GET_BANNERS",
    GET_PRODUCT_CATEGORIES: "GET_PRODUCT_CATEGORIES",
    GET_PRODUCTS: "GET_PRODUCTS",
    ADD_PRODUCT: "ADD_PRODUCT",
    REMOVE_PRODUCT: "REMOVE_PRODUCT"
}